"""added breed colum

Revision ID: 593b7507590c
Revises: 9f01f0900d7f
Create Date: 2024-01-15 18:19:01.872019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '593b7507590c'
down_revision = '9f01f0900d7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('puppies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('breed', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('puppies', schema=None) as batch_op:
        batch_op.drop_column('breed')

    # ### end Alembic commands ###
